name: roadsidepros
description: Roadside Pros lets you request and pay for Roadside Services!

publish_to: 'none' # Remove this line if you are publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.17.0 # Latest stable as of May 2024
  firebase_auth: ^5.10.0 # Latest stable as of May 2024
  google_sign_in: ^6.3.0 # Latest stable as of May 2024

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0 # Recommended for Dart 3.x
  flutter_lints: ^4.0.0 # Recommended lint rules for Flutter

flutter:
  uses-material-design: true