name: roadsidepros

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      # Regenerate Android directory
      - name: Regenerate Android directory
        run: flutter create .

      # Fetch dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build APK
      - name: Build APK
        run: flutter build apk --release

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Cache Clean
      - name: Clean Flutter Build
        run: flutter clean

      # Rename APK
      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Roadside_Pros.apk