name: roadsidepros

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      # Fetch dependencies
      - name: Install dependencies
        run: flutter pub get

      # Clean Flutter Build (if necessary)
      - name: Clean Flutter Build
        run: flutter clean

      # Build APK
      - name: Build APK
        run: flutter build apk --release

      # Debug Build Directory
      - name: Debug Build Directory
        run: ls -R build/app/outputs/

      # Rename APK (if it exists)
      - name: Rename APK
        if: success()
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Roadside_Pros.apk

      # Upload APK (after renaming)
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Roadside_Pros.apk
          path: build/app/outputs/flutter-apk/Roadside_Pros.apk