name: roadsidepros

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      # Regenerate Android directory
      - name: Regenerate Android directory
        run: flutter create .

      # Fetch dependencies
      - name: Install dependencies
        run: flutter pub get

      # Rename Project
      - name: Rename project folder to lowercase
  	run: |
          mv RoadsidePros roadsidepros

      # Build APK
      - name: Build APK
        run: flutter build apk --release