name: roadsidepros

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            android/.gradle
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Clean Flutter Build
        run: flutter clean

      - name: Update Kotlin Version
        run: sed -i 's/ext.kotlin_version = ".*"/ext.kotlin_version = "2.1.0"/' android/build.gradle

      - name: Ensure Gradle Wrapper 8.9
        run: sed -i 's#distributionUrl=.*#distributionUrl=https\\://services.gradle.org/distributions/gradle-8.9-all.zip#' android/gradle/wrapper/gradle-wrapper.properties

      - name: Install Android NDK
        run: yes | sdkmanager "ndk-bundle"

      - name: Set Android NDK Path
        run: echo "ndk.dir=$ANDROID_SDK_ROOT/ndk-bundle" >> android/local.properties

      - name: Debug Android SDK and NDK
        run: |
          ls $ANDROID_SDK_ROOT/ndk || echo "NDK directory missing"
          ls /usr/local/lib/android/ndk || echo "NDK directory missing"

      - name: Build APK
        run: flutter build apk --release -v

      - name: Debug Build Directory
        run: ls -R build/app/outputs/

      - name: Rename APK
        if: success()
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Roadside_Pros.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Roadside_Pros.apk
          path: build/app/outputs/flutter-apk/Roadside_Pros.apk