name: roadsidepros

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      # Fetch dependencies
      - name: Install dependencies
        run: flutter pub get

      # Clean Flutter Build (if necessary)
      - name: Clean Flutter Build
        run: flutter clean

      # Update Kotlin Version in build.gradle
      - name: Update Kotlin Version
        run: |
          sed -i 's/ext.kotlin_version = ".*"/ext.kotlin_version = "2.1.0"/' android/build.gradle

      # Ensure Gradle Wrapper is 8.9
      - name: Ensure Gradle Wrapper 8.9
        run: |
          sed -i 's#distributionUrl=.*#distributionUrl=https\\://services.gradle.org/distributions/gradle-8.9-all.zip#' android/gradle/wrapper/gradle-wrapper.properties

      # Build APK
      - name: Build APK
        run: flutter build apk --release

      # Debug Build Directory
      - name: Debug Build Directory
        run: ls -R build/app/outputs/

      # Rename APK (if it exists)
      - name: Rename APK
        if: success()
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Roadside_Pros.apk

      # Upload APK (after renaming)
      - name: Upload APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Roadside_Pros.apk
          path: build/app/outputs/flutter-apk/Roadside_Pros.apk